[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.7.0"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_VERSION = "12.13.0"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200