# This is a basic workflow to help you get started with Actions

name: Add new episode cron

on: 
  push:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * MON,THU'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: npm install ytdl-core @ffmpeg-installer/ffmpeg fluent-ffmpeg backblaze-b2 mustache
      - run: mkdir -m777 /home/runner/work/js-talks/js-talks/files-to-push/
      - uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs')
            fs.writeFileSync(
              `/home/runner/work/js-talks/js-talks/files-to-push/test.txt`,
              'test'
            );
            const script = require(`${process.env.GITHUB_WORKSPACE}/cron.js`)
            const episodes = require(`${process.env.GITHUB_WORKSPACE}/episodes.json`)
            const template = fs.readFileSync(`${process.env.GITHUB_WORKSPACE}/template.md`).toString()
            const readme = fs.readFileSync(`${process.env.GITHUB_WORKSPACE}/README.md`).toString()
            const {
              output,
              episode,
              episodeName,
              newReadme,
              newEpisodes
            } = await script(
              `${{ secrets.GITHUB_TOKEN }}`,
              episodes,
              `${{ secrets.B2_APP_KEY_ID }}`,
              `${{ secrets.B2_APP_KEY }}`,
              template,
              readme
            )
            fs.writeFileSync(
              `/home/runner/work/js-talks/js-talks/files-to-push/${episodeName}.md`,
              output
            );
            fs.writeFileSync(`/home/runner/work/js-talks/js-talks/files-to-push/README.md`, newReadme);
            fs.writeFileSync(
              `/home/runner/work/js-talks/js-talks/files-to-push/episodes.json`,
              episodes
            );
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: |
                files-to-push/*.md
                files-to-push/episodes.json
            commit-msg: Add new episode from GitHub Action
            github-token: ${{ secrets.GITHUB_TOKEN }}